// (c) 2022 Long Ly. All rights reserved.

#pragma once

/* **************************************************/
/* DO NOT EDIT THIS FILE MANUALLY!                  */
/* **************************************************/
/* This file is autogenerated by a python script.   */
/* See: gameplaytags_to_cpp.py                      */
/* **************************************************/
/* DO NOT EDIT THIS FILE MANUALLY!                  */
/* **************************************************/

#define GTag_Animation TEXT("Animation")
#define GTag_Animation_Poses TEXT("Animation.Poses")
#define GTag_Animation_Poses_BaseLayer TEXT("Animation.Poses.BaseLayer")
#define GTag_Animation_Poses_BaseLayer_Default TEXT("Animation.Poses.BaseLayer.Default")
#define GTag_Animation_Poses_OverlayLayer TEXT("Animation.Poses.OverlayLayer")
#define GTag_Animation_Poses_OverlayLayer_Default TEXT("Animation.Poses.OverlayLayer.Default")
#define GTag_GameplayCue TEXT("GameplayCue")
